### ISSUE TITLE
not able to compile with scala 2.11.7 on mac os

### ISSUE THREAD

**Issue by sonalgupta** [gangeli/qry#3]
What scala version you are using? I'm unable to compile this on my mac os x. I also downloaded the typesafe-config jar and put it in plugin_lib/typesafe-config-1.0.0.jar

Do I need to install more stuff?

src/qry/PBSPlugin.scala:109: error: type mismatch;
 found   : Unit
 required: Option[Int]
    Thread.sleep(5000)
                ^
src/qry/Qry.scala:367: error: object JLineReader is not a member of package scala.tools.nsc.interpreter
    import scala.tools.nsc.interpreter.{IMain,JLineReader,JLineCompletion}
           ^
src/qry/Qry.scala:377: error: not found: type JLineReader
    val reader:JLineReader = new JLineReader(new JLineCompletion(interpreter))
               ^
src/qry/Qry.scala:377: error: not found: type JLineReader
    val reader:JLineReader = new JLineReader(new JLineCompletion(interpreter))
                                 ^

**Comment by gangeli** [comment]
Clearly I don't read GitHub issues often enough... Maybe this is a Scala incompatibility error? My recommendation would be to just use the pre-built `qry.jar` (which has all dependencies bundled -- only needs Java) from one of the releases (https://github.com/gangeli/qry/releases), as you pretty much never want to link against the library programmatically anyways.
